import { createContext, useContext, useState, useEffect } from 'react';

// Çeviriler
const translations = {
  tr: {
      site: {
        title: 'Koç Platformu',
      },
      lang: {
        turkish: 'Türkçe',
        english: 'English',
        flag: {
          tr: '🇹🇷',
          en: '🇬🇧',
        },
      },
    // Navigation
    nav: {
      home: 'Ana Sayfa',
      findCoach: 'Koç Bul',
      messages: 'Mesajlar',
      profile: 'Profilim',
      settings: 'Site Ayarları',
      login: 'Giriş Yap',
      register: 'Kayıt Ol',
      logout: 'Çıkış Yap',
    },
    // Landing Page
    landing: {
      heroTitle: 'Hayallerinize Ulaşın',
      heroSubtitle: 'Profesyonel koçlarla tanışın ve potansiyelinizi keşfedin',
      findCoachBtn: 'Koç Bul',
      becomeCoachBtn: 'Koç Ol',
      featuresTitle: 'Neden Bizi Tercih Etmelisiniz?',
      feature1Title: 'Uzman Koçlar',
      feature1Desc: 'Alanında uzman, sertifikalı koçlarla çalışın',
      feature2Title: 'Esnek Zamanlama',
      feature2Desc: 'Size uygun zamanlarda randevu alın',
      feature3Title: 'Güvenli İletişim',
      feature3Desc: 'Koçunuzla güvenli bir şekilde iletişim kurun',
      statsCoaches: 'Aktif Koç',
      statsMessages: 'Mesaj Gönderildi',
      statsUsers: 'Mutlu Kullanıcı',
      satisfactionTitle: 'Memnuniyetini Değerlendir',
      satisfactionSubtitle: 'Deneyimini 1-5 arasında puanla, istersen kısa bir yorum bırak.',
      satisfactionAria: 'Memnuniyet puanı',
      satisfactionThanks: 'Geri bildiriminiz için teşekkürler! 🎉',
      satisfactionCommentPlaceholder: 'Kısa bir yorum yaz (isteğe bağlı)...',
      satisfactionSubmit: 'Gönder',
      topCoachesTitle: 'En Çok Tercih Edilen Koçlar',
      viewAll: 'Tümünü Gör',
      contactWithoutRegister: 'Kayıt olmadan koçlarla iletişime geçebilirsiniz!',
    },
    // Coaches Page
    coaches: {
      title: 'Koç Bul',
      subtitle: 'Size en uygun koçu bulun',
      contactWithoutRegister: 'Kayıt olmadan koçlarla iletişime geçebilirsiniz!',
      searchPlaceholder: 'İsim veya uzmanlık alanı ara...',
      filterSpecialty: 'Uzmanlık Alanı',
      filterAllSpecialties: 'Tüm Alanlar',
      filterMinPrice: 'Min Fiyat',
      filterMaxPrice: 'Max Fiyat',
      filterMinExp: 'Min Deneyim (Yıl)',
      filterMaxExp: 'Max Deneyim (Yıl)',
      sortBy: 'Sırala',
      sortDefault: 'Varsayılan',
      sortPriceAsc: 'Fiyat (Düşük → Yüksek)',
      sortPriceDesc: 'Fiyat (Yüksek → Düşük)',
      sortNameAsc: 'İsim (A → Z)',
      sortNameDesc: 'İsim (Z → A)',
      sortMsgDesc: 'En Çok Mesaj',
      sortMsgAsc: 'En Az Mesaj',
      sortExpDesc: 'En Deneyimli',
      sortExpAsc: 'En Az Deneyimli',
      clearFilters: 'Filtreleri Temizle',
      noResults: 'Aramanıza uygun koç bulunamadı',
      hourlyRate: '/saat',
      yearsExp: 'yıl deneyim',
      messages: 'mesaj',
      viewProfile: 'Profili Gör',
      contact: 'İletişime Geç',
      loading: 'Koçlar yükleniyor...',
      sortRatingDesc: 'Puan (Yüksek → Düşük)',
      sortRatingAsc: 'Puan (Düşük → Yüksek)',
      ratingLabel: 'Puan',
    },
    // Coach Profile
    coachProfile: {
      breadcrumb: 'Koç Profili',
      about: 'Hakkında',
      specialties: 'Uzmanlık Alanları',
      experience: 'Deneyim',
      hourlyRate: 'Saatlik Ücret',
      totalMessages: 'Toplam Mesaj',
      contactTitle: 'İletişime Geç',
      yourName: 'Adınız Soyadınız',
      yourEmail: 'E-posta Adresiniz',
      yourMessage: 'Mesajınız',
      sendMessage: 'Mesaj Gönder',
      sending: 'Gönderiliyor...',
      messageSent: 'Mesajınız gönderildi!',
      undoMessage: 'saniye içinde geri alabilirsiniz',
      undo: 'Geri Al',
      fillAllFields: 'Lütfen tüm alanları doldurun',
      undoCancelled: 'Mesaj gönderimi iptal edildi. Mesajınızı düzenleyebilirsiniz.',
      undoFailed: 'Geri alma işlemi başarısız oldu.',
      notFound: 'Koç bulunamadı',
      noDescription: 'Henüz bir açıklama eklenmemiş.',
      contactPrompt: 'Bu koç ile iletişime geçmek için aşağıdaki butona tıklayarak mesaj gönderebilirsiniz.',
      rateCoachTitle: 'Koçu Değerlendir',
      rateCount: 'oy',
      rateYourRatingAria: 'puan',
      rateCommentPlaceholder: 'Kısa bir yorum ekleyin (isteğe bağlı)...',
      rateSubmit: 'Puanı Gönder',
    },
    // Messages
    messages: {
      title: 'Mesajlarım',
      subtitle: 'Size gönderilen mesajları görüntüleyin ve yönetin',
      noMessages: 'Henüz mesajınız yok',
      unread: 'Okunmamış',
      read: 'Okunmuş',
      markAsRead: 'Okundu İşaretle',
      markAsUnread: 'Okunmadı İşaretle',
      delete: 'Sil',
      deleteAll: 'Tümünü Sil',
      deleteAllConfirm: 'Tüm mesajları silmek istediğinizden emin misiniz?',
      filterAll: 'Tümü',
      filterUnread: 'Okunmamış',
      filterRead: 'Okunmuş',
      filterByDate: 'Tarihe Göre',
      dateNewest: 'En Yeni',
      dateOldest: 'En Eski',
      dateToday: 'Bugün',
      dateThisWeek: 'Bu Hafta',
      dateThisMonth: 'Bu Ay',
      messageDeleted: 'Mesaj silindi',
      allDeleted: 'Tüm mesajlar silindi',
      from: 'Kimden',
      date: 'Tarih',
      loading: 'Mesajlar yükleniyor...',
      justNow: 'Az önce',
      photoHint: 'Cihazınızdan profil resmi yükleyin',
      currentImage: 'Mevcut Resim',
      noProfileImage: 'Henüz profil resmi yok',
      imageFormats: 'JPG, PNG veya GIF (Maks. 2MB)',
      chooseImage: 'Resim Seç',
      updateProfileImageBtn: 'Profil Resmini Güncelle',
      passwordHint: 'Hesap güvenliğiniz için düzenli olarak şifrenizi değiştirin',
      minutesAgo: '{{count}} dakika önce',
      hoursAgo: '{{count}} saat önce',
      daysAgo: '{{count}} gün önce',
    },
    // Keyboard Shortcuts
    shortcuts: {
      title: '⌨️ Klavye Kısayolları',
      helper: 'Uygulamayı daha hızlı kullanmak için klavye kısayollarından yararlanın.',
      hint: '(Shneiderman Kural 2: Uzman kullanıcılar için kısayollar)',
      showShortcuts: 'Klavye kısayollarını göster',
      goHome: 'Ana sayfaya git',
      goSettings: 'Ayarlar sayfasına git',
      toggleDark: 'Koyu modu aç/kapat',
      closeModal: 'Modalı kapat',
      nextElement: 'Bir sonraki elemana git',
      prevElement: 'Bir önceki elemana git',
      submit: 'Formu gönder / Butonu aktive et',
      tip: 'İpucu: Input alanında yazarken kısayollar devre dışıdır. Form dışında ? tuşuna basarak bu yardımı açabilirsiniz.',
    },
    // Login
    login: {
      title: 'Giriş Yap',
      subtitle: 'Koç hesabınıza giriş yapın',
      email: 'E-posta',
      password: 'Şifre',
      rememberMe: 'Beni Hatırla',
      forgotPassword: 'Şifremi Unuttum',
      loginBtn: 'Giriş Yap',
      loggingIn: 'Giriş yapılıyor...',
      noAccount: 'Hesabınız yok mu?',
      registerLink: 'Kayıt Ol',
      coachOnly: 'Yalnızca koç olarak giriş yapabilirsiniz',
      forgotPrompt: 'Şifre sıfırlama talimatları email adresinize gönderilecektir.',
      send: 'Gönder',
    },
    // Register
    register: {
      title: 'Koç Olarak Kayıt Ol',
      subtitle: 'Uzmanlığınızı paylaşın ve insanlara yardımcı olun',
      professionalInfo: 'Profesyonel Bilgiler',
      fullName: 'Ad Soyad',
      email: 'E-posta',
      password: 'Şifre',
      passwordHint: 'Hesabınızın güvenliği için güçlü bir şifre kullanın (en az 6 karakter).',
      confirmPassword: 'Şifre Tekrar',
      bio: 'Hakkınızda',
      coachOnlyNotice: 'Bu platform yalnızca koç kaydı içindir',
      personalInfo: 'Kişisel Bilgiler',
      bioPlaceholder: 'Deneyimleriniz, yaklaşımınız ve insanlara nasıl yardımcı olabileceğinizi anlatın...',
      bioHint: 'Bu bilgi profilinizde görünecektir',
      hourlyRate: 'Saatlik Ücret (₺)',
      hourlyRateLabel: 'Saatlik Ücret (₺) *',
      experience: 'Deneyim (Yıl)',
      yearsExperience: 'Deneyim (Yıl)',
      specialties: 'Uzmanlık Alanları',
      specialtyPlaceholder: 'Uzmanlık alanı yazın veya aşağıdan seçin',
      addSpecialty: 'Alan Ekle',
      addByEnter: 'Enter tuşuna basarak da ekleyebilirsiniz',
      popularSpecialties: 'Popüler alanlar:',
      selectedSpecialties: 'Seçili alanlar:',
      careerCoaching: 'Kariyer Koçluğu',
        addSpecialtyAria: 'Uzmanlık alanı ekle',
      lifeCoaching: 'Yaşam Koçluğu',
      leadership: 'Liderlik',
      personalDev: 'Kişisel Gelişim',
      workLife: 'İş Hayatı',
      motivation: 'Motivasyon',
      fitness: 'Fitness',
      health: 'Sağlık',
      nutrition: 'Beslenme',
      mindfulness: 'Mindfulness',
      relationships: 'İlişkiler',
      finance: 'Finans',
      entrepreneurship: 'Girişimcilik',
      stress: 'Stres Yönetimi',
      registerBtn: 'Kayıt Ol',
      registering: 'Kayıt yapılıyor...',
      hasAccount: 'Zaten hesabınız var mı?',
      loginLink: 'Giriş Yap',
      validation: {
        emailRequired: 'E-posta gereklidir',
        invalidEmail: 'Geçerli bir e-posta girin',
        passwordRequired: 'Şifre gereklidir',
        passwordTooShort: 'Şifre en az 6 karakter olmalı',
        passwordsDontMatch: 'Şifreler eşleşmiyor',
        nameRequired: 'Ad Soyad gereklidir',
        hourlyRateRequired: 'Saatlik ücret gereklidir',
        hourlyRateInvalid: 'Geçerli bir ücret girin',
        specialtiesRequired: 'En az bir uzmanlık alanı seçin',
      },
    },
    // Dashboard
    dashboard: {
      title: 'Profilim',
      subtitle: 'Koç profilinizi görüntüleyin ve düzenleyin',
      tabProfile: 'Profil Bilgileri',
      tabPhoto: 'Profil Resmi',
      tabSecurity: 'Şifre Değiştir',
      saveChanges: 'Değişiklikleri Kaydet',
      saving: 'Kaydediliyor...',
      uploadPhoto: 'Fotoğraf Yükle',
      currentPassword: 'Mevcut Şifre',
      newPassword: 'Yeni Şifre',
      confirmNewPassword: 'Yeni Şifre Tekrar',
      changePassword: 'Şifreyi Değiştir',
      deleteAccountTitle: 'Hesabı Sil',
      deleteAccountDesc: 'Hesabınızı ve tüm mesajlarınızı kalıcı olarak silmek için bu seçeneği kullanın.',
      deleteAccountBtn: 'Hesabımı Sil',
      deleteConfirm: 'Hesabınızı kalıcı olarak silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
      editProfile: 'Profili Düzenle',
      profileUpdated: 'Profiliniz başarıyla güncellendi',
      profileUpdateError: 'Profil güncellenirken bir hata oluştu',
      minSpecialtyRequired: 'En az bir uzmanlık alanı gereklidir',
      fileTooLarge: 'Dosya boyutu en fazla 2MB olmalıdır',
      invalidImageFile: 'Lütfen bir resim dosyası seçin',
      profileImageUpdated: 'Profil resmi güncellendi',
      profileImageUpdateError: 'Profil resmi güncellenirken bir hata oluştu',
      photoHint: 'Cihazınızdan profil resmi yükleyin',
      currentImage: 'Mevcut Resim',
      noProfileImage: 'Henüz profil resmi yok',
      imageFormats: 'JPG, PNG veya GIF (Maks. 2MB)',
      chooseImage: 'Resim Seç',
      updateProfileImageBtn: 'Profil Resmini Güncelle',
      passwordHint: 'Hesap güvenliğiniz için düzenli olarak şifrenizi değiştirin',
      fillAllFields: 'Lütfen tüm alanları doldurun',
      passwordTooShort: 'Yeni şifre en az 6 karakter olmalıdır',
      passwordsDontMatch: 'Yeni şifreler eşleşmiyor',
      passwordChanged: 'Şifreniz başarıyla değiştirildi',
      passwordChangeError: 'Şifre değiştirilirken bir hata oluştu',
    },
    // Settings
    settings: {
      title: 'Site Ayarları',
      subtitle: 'Görünüm tercihlerinizi yönetin',
      appearance: 'Görünüm',
      theme: 'Tema',
      lightMode: 'Açık Mod',
      darkMode: 'Koyu Mod',
      fontSize: 'Yazı Boyutu',
      small: 'Küçük',
      medium: 'Orta',
      large: 'Büyük',
      extraLarge: 'Çok Büyük',
      language: 'Dil',
      languageHelp: 'Site dilini seçin',
      languageTurkishDesc: 'Türkçe arayüz',
      languageEnglishDesc: 'English interface',
      themeHelp: 'Sitenin görünümünü seçin (Erişilebilirlik özelliği - Göz yorgunluğunu azaltır)',
      lightDesc: 'Standart beyaz arka plan',
      darkDesc: 'Koyu arka plan - Göz yorgunluğunu azaltır',
      fontSizeHelp: 'Sitenin yazı boyutunu ayarlayın (Erişilebilirlik özelliği - Görme zorluğu olanlar için)',
      accessibilityInfo: '♿ Erişilebilirlik: Bu özellik özellikle görme zorluğu olan kullanıcılar için tasarlanmıştır. Yazı boyutunu ihtiyacınıza göre ayarlayarak siteyi daha rahat kullanabilirsiniz.',
    },
    // Common
    common: {
      loading: 'Yükleniyor...',
      error: 'Bir hata oluştu',
      success: 'Başarılı',
      cancel: 'İptal',
      confirm: 'Onayla',
      save: 'Kaydet',
      edit: 'Düzenle',
      delete: 'Sil',
      back: 'Geri',
      next: 'İleri',
      photoHint: 'Upload a profile image from your device',
      currentImage: 'Current Image',
      noProfileImage: 'No profile image yet',
      imageFormats: 'JPG, PNG or GIF (Max 2MB)',
      chooseImage: 'Choose Image',
      updateProfileImageBtn: 'Update Profile Image',
      passwordHint: 'For account security, change your password regularly',
      search: 'Ara',
      clear: 'Temizle',
      yes: 'Evet',
      no: 'Hayır',
      add: 'Ekle',
      retry: 'Tekrar Dene',
      remove: 'Kaldır',
    },
    // Footer
    footer: {
      description: 'Profesyonel koçluk hizmetleri platformu',
      rights: 'Tüm hakları saklıdır.',
      links: 'Hızlı Linkler',
      contact: 'İletişim',
    },
  },
  en: {
      site: {
        title: 'Coach Platform',
      },
      lang: {
        turkish: 'Türkçe',
        english: 'English',
        flag: {
          tr: '🇹🇷',
          en: '🇬🇧',
        },
      },
    // Navigation
    nav: {
      home: 'Home',
      findCoach: 'Find Coach',
      messages: 'Messages',
      profile: 'My Profile',
      settings: 'Website Settings',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
    },
    // Landing Page
    landing: {
      heroTitle: 'Reach Your Dreams',
      heroSubtitle: 'Meet professional coaches and discover your potential',
      findCoachBtn: 'Find Coach',
      becomeCoachBtn: 'Become a Coach',
      featuresTitle: 'Why Choose Us?',
      feature1Title: 'Expert Coaches',
      feature1Desc: 'Work with certified experts in their field',
      feature2Title: 'Flexible Scheduling',
      feature2Desc: 'Book appointments at times that suit you',
      feature3Title: 'Secure Communication',
      feature3Desc: 'Communicate securely with your coach',
      statsCoaches: 'Active Coaches',
      statsMessages: 'Messages Sent',
      statsUsers: 'Happy Users',
      satisfactionTitle: 'Rate Your Satisfaction',
      satisfactionSubtitle: 'Rate your experience from 1–5 and leave a short comment if you like.',
      satisfactionAria: 'Satisfaction rating',
      satisfactionThanks: 'Thanks for your feedback! 🎉',
      satisfactionCommentPlaceholder: 'Write a short comment (optional)...',
      satisfactionSubmit: 'Submit',
      topCoachesTitle: 'Most Preferred Coaches',
      viewAll: 'View All',
      contactWithoutRegister: 'Contact coaches without registration!',
    },
    // Coaches Page
    coaches: {
      title: 'Find a Coach',
      subtitle: 'Find the coach that suits you best',
      contactWithoutRegister: 'Contact coaches without registration!',
      searchPlaceholder: 'Search by name or specialty...',
      filterSpecialty: 'Specialty',
      filterAllSpecialties: 'All Specialties',
      filterMinPrice: 'Min Price',
      filterMaxPrice: 'Max Price',
      filterMinExp: 'Min Experience (Years)',
      filterMaxExp: 'Max Experience (Years)',
      sortBy: 'Sort By',
      sortDefault: 'Default',
      sortPriceAsc: 'Price (Low → High)',
      sortPriceDesc: 'Price (High → Low)',
      sortNameAsc: 'Name (A → Z)',
      sortNameDesc: 'Name (Z → A)',
      sortMsgDesc: 'Most Messages',
      sortMsgAsc: 'Least Messages',
      sortExpDesc: 'Most Experienced',
      sortExpAsc: 'Least Experienced',
      clearFilters: 'Clear Filters',
      noResults: 'No coaches found matching your search',
      hourlyRate: '/hour',
      yearsExp: 'years experience',
      messages: 'messages',
      viewProfile: 'View Profile',
      contact: 'Contact',
      loading: 'Loading coaches...',
      sortRatingDesc: 'Rating (High → Low)',
      sortRatingAsc: 'Rating (Low → High)',
      ratingLabel: 'Rating',
    },
    // Coach Profile
    coachProfile: {
      breadcrumb: 'Coach Profile',
      about: 'About',
      specialties: 'Specialties',
      experience: 'Experience',
      hourlyRate: 'Hourly Rate',
      totalMessages: 'Total Messages',
      contactTitle: 'Get in Touch',
      yourName: 'Your Name',
      yourEmail: 'Your Email',
      yourMessage: 'Your Message',
      sendMessage: 'Send Message',
      sending: 'Sending...',
      messageSent: 'Your message has been sent!',
      undoMessage: 'seconds to undo',
      undo: 'Undo',
      fillAllFields: 'Please fill in all fields',
      undoCancelled: 'Message send cancelled. You can edit your message.',
      undoFailed: 'Undo operation failed.',
      notFound: 'Coach not found',
      noDescription: 'No description yet.',
      contactPrompt: 'Click the button below to send a message to this coach.',
      rateCoachTitle: 'Rate This Coach',
      rateCount: 'votes',
      rateYourRatingAria: 'rating',
      rateCommentPlaceholder: 'Add a short comment (optional)...',
      rateSubmit: 'Submit Rating',
    },
    // Messages
    messages: {
      title: 'My Messages',
      subtitle: 'View and manage messages sent to you',
      noMessages: 'No messages yet',
      unread: 'Unread',
      read: 'Read',
      markAsRead: 'Mark as Read',
      markAsUnread: 'Mark as Unread',
      delete: 'Delete',
      deleteAll: 'Delete All',
      deleteAllConfirm: 'Are you sure you want to delete all messages?',
      filterAll: 'All',
      filterUnread: 'Unread',
      filterRead: 'Read',
      filterByDate: 'Filter by Date',
      dateNewest: 'Newest',
      dateOldest: 'Oldest',
      dateToday: 'Today',
      dateThisWeek: 'This Week',
      dateThisMonth: 'This Month',
      messageDeleted: 'Message deleted',
      allDeleted: 'All messages deleted',
      from: 'From',
      date: 'Date',
      loading: 'Loading messages...',
      justNow: 'Just now',
      minutesAgo: '{{count}} minutes ago',
      hoursAgo: '{{count}} hours ago',
      daysAgo: '{{count}} days ago',
    },
    // Keyboard Shortcuts
    shortcuts: {
      title: '⌨️ Keyboard Shortcuts',
      helper: 'Use keyboard shortcuts to navigate faster.',
      hint: '(Shneiderman Rule 2: Shortcuts for expert users)',
      showShortcuts: 'Show keyboard shortcuts',
      goHome: 'Go to home',
      goSettings: 'Go to settings',
      toggleDark: 'Toggle dark mode',
      closeModal: 'Close modal',
      nextElement: 'Focus next element',
      prevElement: 'Focus previous element',
      submit: 'Submit form / Activate button',
      tip: 'Tip: Shortcuts are disabled while typing in inputs. Press ? anywhere else to open this help.',
    },
    // Login
    login: {
      title: 'Login',
      subtitle: 'Sign in to your coach account',
      email: 'Email',
      password: 'Password',
      rememberMe: 'Remember Me',
      forgotPassword: 'Forgot Password',
      loginBtn: 'Login',
      loggingIn: 'Logging in...',
      noAccount: "Don't have an account?",
      registerLink: 'Register',
      coachOnly: 'Only coaches can log in here',
      forgotPrompt: 'Password reset instructions will be sent to your email address.',
      send: 'Send',
    },
    // Register
    register: {
      title: 'Register as a Coach',
      subtitle: 'Share your expertise and help others',
      professionalInfo: 'Professional Information',
      fullName: 'Full Name',
      email: 'Email',
      password: 'Password',
      passwordHint: 'Use a strong password for your account (at least 6 characters).',
      confirmPassword: 'Confirm Password',
      bio: 'About You',
      coachOnlyNotice: 'This platform is for coach registrations only',
      personalInfo: 'Personal Information',
      bioPlaceholder: 'Describe your experience, approach and how you help people...',
      bioHint: 'This information will appear on your profile',
      hourlyRate: 'Hourly Rate (₺)',
      hourlyRateLabel: 'Hourly Rate (₺) *',
      experience: 'Experience (Years)',
      yearsExperience: 'Experience (Years)',
      specialties: 'Specialties',
      specialtyPlaceholder: 'Type a specialty or pick from below',
      addSpecialty: 'Add Specialty',
      addByEnter: 'Press Enter to add as well',
      popularSpecialties: 'Popular specialties:',
      selectedSpecialties: 'Selected specialties:',
      careerCoaching: 'Career Coaching',
      addSpecialtyAria: 'Add specialty',
      lifeCoaching: 'Life Coaching',
      leadership: 'Leadership',
      personalDev: 'Personal Development',
      workLife: 'Work Life',
      motivation: 'Motivation',
      fitness: 'Fitness',
      health: 'Health',
      nutrition: 'Nutrition',
      mindfulness: 'Mindfulness',
      relationships: 'Relationships',
      finance: 'Finance',
      entrepreneurship: 'Entrepreneurship',
      stress: 'Stress Management',
      registerBtn: 'Register',
      registering: 'Registering...',
      hasAccount: 'Already have an account?',
      loginLink: 'Login',
      validation: {
        emailRequired: 'Email is required',
        invalidEmail: 'Please enter a valid email',
        passwordRequired: 'Password is required',
        passwordTooShort: 'Password must be at least 6 characters',
        passwordsDontMatch: 'Passwords do not match',
        nameRequired: 'Full name is required',
        hourlyRateRequired: 'Hourly rate is required',
        hourlyRateInvalid: 'Please enter a valid hourly rate',
        specialtiesRequired: 'Please select at least one specialty',
      },
    },
    // Dashboard
    dashboard: {
      title: 'My Profile',
      subtitle: 'View and edit your coach profile',
      tabProfile: 'Profile Info',
      tabPhoto: 'Profile Photo',
      tabSecurity: 'Change Password',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      uploadPhoto: 'Upload Photo',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      changePassword: 'Change Password',
      deleteAccountTitle: 'Delete Account',
      deleteAccountDesc: 'Use this option to permanently delete your account and all messages.',
      deleteAccountBtn: 'Delete My Account',
      deleteConfirm: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
      editProfile: 'Edit Profile',
      profileUpdated: 'Profile updated successfully',
      profileUpdateError: 'An error occurred while updating the profile',
      minSpecialtyRequired: 'At least one specialty is required',
      fileTooLarge: 'File size must be at most 2MB',
      invalidImageFile: 'Please select an image file',
      profileImageUpdated: 'Profile image updated',
      profileImageUpdateError: 'An error occurred while updating profile image',
      photoHint: 'Upload a profile image from your device',
      currentImage: 'Current Image',
      noProfileImage: 'No profile image yet',
      imageFormats: 'JPG, PNG or GIF (Max 2MB)',
      chooseImage: 'Choose Image',
      updateProfileImageBtn: 'Update Profile Image',
      passwordHint: 'For account security, change your password regularly',
      fillAllFields: 'Please fill in all fields',
      passwordTooShort: 'New password must be at least 6 characters',
      passwordsDontMatch: 'New passwords do not match',
      passwordChanged: 'Your password has been changed',
      passwordChangeError: 'An error occurred while changing the password',
    },
    // Settings
    settings: {
      title: 'Website Settings',
      subtitle: 'Manage your appearance preferences',
      appearance: 'Appearance',
      theme: 'Theme',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      fontSize: 'Font Size',
      small: 'Small',
      medium: 'Medium',
      large: 'Large',
      extraLarge: 'Extra Large',
      language: 'Language',
      languageHelp: 'Choose the site language',
      languageTurkishDesc: 'Turkish interface',
      languageEnglishDesc: 'English interface',
      themeHelp: 'Choose the site appearance (accessibility feature - reduces eye fatigue)',
      lightDesc: 'Standard light background',
      darkDesc: 'Dark background - reduces eye fatigue',
      fontSizeHelp: 'Adjust the site font size (accessibility feature - for users with visual difficulty)',
      accessibilityInfo: '♿ Accessibility: This feature is designed for users with visual difficulties. Adjust the font size to make the site easier to use.',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'An error occurred',
      success: 'Success',
      cancel: 'Cancel',
      add: 'Add',
      confirm: 'Confirm',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      back: 'Back',
      next: 'Next',
      search: 'Search',
      clear: 'Clear',
      yes: 'Yes',
      no: 'No',
      retry: 'Retry',
      remove: 'Remove',
    },
    // Footer
    footer: {
      description: 'Professional coaching services platform',
      rights: 'All rights reserved.',
      links: 'Quick Links',
      contact: 'Contact',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    
    for (const k of keys) {
      if (value && value[k]) {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }
    
    return value;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'tr' ? 'en' : 'tr');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;

